### ISSUE TITLE
About preparing dataset.

### ISSUE THREAD

**Issue by kimsekeun** [ales-git/DeepCADRADS#1]
Dear authors,

Thank you for your work.
I wonder how you stretched CCTA and reconstructed it to straighten views.
There may be some open-source code; please share your experience.
or any commercial s/w that you used for your dataset
Thanks.

**Comment by ales-git** [comment]
Dear kimsekeun,
thank you for your interest in our work. Unfortunately we do not have open-source code for that part as it was directly performed by the clinicians using proprietary software included in the CT scanners. More details about the scanners and acquisition protocols can be find in the paper DOI: 10.1016/j.cmpb.2023.107989
